### ISSUE TITLE
Erreur librarie non trouvée : command-not-found==0.3

### ISSUE THREAD

**Issue by bilbaoba** [LE2P/DeepRun-GUI#1]
Lors du 

```bash
pip install -r settings/requirements.txt
```

ERROR: Could not find a version that satisfies the requirement command-not-found==0.3 (from versions: none)
ERROR: No matching distribution found for command-not-found==0.3

**Comment by bilbaoba** [comment]
@christophe-lkc : Peut être, on peut simplement enlever le requirements, étant données que l'installation de GDAL est spécifique.

**Comment by christophe-lkc** [comment]
it's corrected, thanks
